export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  DECREASE_ITEM: "DECREASE_ITEM",
  CLEAR_CART: "CLEAR_CART",
  CREATE_USER_CART: "CREATE_USER_CART",
  SET_CART_FROM_FIREBASE: "SET_CART_FROM_FIREBASE",
};
